version: '3.8'

services:
    php:
        container_name: c-scoreboard
        image: i-scoreboard
        build:
          context: ./
          dockerfile: ./docker/php/Dockerfile
        volumes:
         - ./:/opt/project